spring:
  application:
    name: eureka-server     #????,???
  security:
    user:
      name: user           #??BASIC???????
      password: 123456      #??BASIC???????
server:
  port: 8080                #???Eureka?????
eureka:
  client:
    registerWithEureka: false      #??????
    fetchRegistry: false          #?????????????????????????????????
                                #???????????????????????????????????
    serviceUrl:
      defaultZone: http://user:123456@localhost:8080/eureka/  #?????????http://??:??@????:??/Eureka/
  server:
    renewalPercentThreshold: 0.49    #?????????????1????????